# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit a model with MCMC
#'
#' Run MCMC on a model compiled using \code{build_model}.
#'
#' Uses the Differential Evolution MCMC algorithm to sample from the posterior distribution
#' of a model's parameters.
#'
#' @param model the model built using \code{build_model}.
#' @param burn_in number of iterations used for burn-in.
#' @param iterations number of iterations used for sampling.
#' @param chains number of chains used for model fitting. It is recommended to use twice as
#'     many chains as there are parameters. The default value of 0 adopts this behaviour.
#' @param threads number of threads to run fitting over in parallel.
#' @param verbose \code{TRUE} to provide more detailed updates on the posterior during fitting.
#' @param seed seeds the random number generator used by the MCMC algorithm.
#' @return A \code{data.frame} containing posterior samples for the model parameters,
#'     in addition to the log probability of the sample (\code{lp}), log likelihood (\code{ll}),
#'     iteration (\code{trial}) and chain number (\code{chain}).
#'
#' @examples
#' model = make_model("test", c(x = "N 0 1", y = "N 0 1"), "ll += -(x + y) * (x + y);")
#' RCppMCMC(model)
#'
#' @export
RCppMCMC <- function(model, burn_in = 500L, iterations = 500L, chains = 0L, threads = 1L, verbose = FALSE, seed = 0L) {
    .Call('_RCppMCMC_RCppMCMC', PACKAGE = 'RCppMCMC', model, burn_in, iterations, chains, threads, verbose, seed)
}

